name: 'DingTalk Notification'
description: 'Send messages to DingTalk via Golang CLI'

inputs:
  webhook:
    description: '钉钉 Webhook 地址'
    required: true
  secret:
    description: '加签密钥（可选）'
    required: false
    default: ""
  message:
    description: '消息内容'
    required: true
  at_mobiles:
    description: '@手机号（逗号分隔，可选）'
    required: false
    default: ""
  markdown:
    description: '是否使用 Markdown'
    required: false
    default: "false"
  title:
    description: 'Markdown 标题（可选）'
    required: false
    default: "Notification"

runs:
  using: docker
  image: 'docker://ghcr.io/mingcai-toolkit/dingtalk-action:v1.0.1'

  entrypoint: "/usr/local/bin/dingtalk-action"
  args:
    - send
    - "--webhook=${{ inputs.webhook }}"
    - "--secret=${{ inputs.secret }}"
    - "--msg=${{ inputs.message }}"
    - "--at=${{ inputs.at_mobiles }}"
    - "--md=${{ inputs.markdown }}"
    - "--title=${{ inputs.title }}"
